# Generated by Django 5.2.1 on 2025-06-02 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_alter_appointment_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_active_appointment',
        ),
    ]
