# Generated by Django 5.2.1 on 2025-05-19 01:26

import barbershop.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name=barbershop.users.models.User),
        ),
    ]
