# Generated by Django 5.2.1 on 2025-06-08 15:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_carouselimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselimage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='carouselimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
